version: '3'
services:
  api:
    # build: . #if image is not present it will build
    image: faizolam/fastapi
    depends_on: 
      - postgres
    ports:
      - 80:8000 #-<port on localhost>:<port on container>

    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # env_file: #if you don't want to write all of your environment var you can point the .env file.
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    # command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

    ## The depends_on directive ensures that the api service starts only after the postgres service is started, which is useful for applications that depend on a database being available
    # depends_on: 
    #   - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: